feat: Add a second state
To make this work I changed process to return the sm parameter. Without
this I got a compile error:

 $ cargo run
    Compiling expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/exper-traits-1)
 error[E0506]: cannot assign to `mysm.current_state` because it is borrowed
   --> src/main.rs:71:5
    |
 69 |     mysm.current_state.process(&mut mysm, &msg);
    |                                --------- borrow of `mysm.current_state` occurs here
 70 |
 71 |     mysm.current_state = &s2;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     assignment to borrowed `mysm.current_state` occurs here
    |     borrow later used here

 For more information about this error, try `rustc --explain E0506`.
 error: could not compile `expr-traits-1` due to previous error

I also cleaned up and added some more debug output.