feat: Add states and current_state_index
Remove current_state.

This still causes error[E0503]:

 $ cargo run
    Compiling expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/exper-traits-1)
 error[E0503]: cannot use `sm.data1` because it was mutably borrowed
   --> src/main.rs:73:13
    |
 54 |     sm.states[sm.current_state_idx].process(&mut sm, &msg);
    |                                             ------- borrow of `sm` occurs here
 ...
 73 |     let x = sm.data1;
    |             ^^^^^^^^
    |             |
    |             use of borrowed `sm`
    |             borrow later used here

 For more information about this error, try `rustc --explain E0503`.
 error: could not compile `expr-traits-1` due to previous error