feat: make sm non-mutable in process and dispatch
And don't return sm to see if that fixes E0506?

No, still get E0506 error:

 $ cargo run
    Compiling expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/exper-traits-1)
 error[E0506]: cannot assign to `sm.current_state` because it is borrowed
   --> src/main.rs:76:5
    |
 74 |     sm.dispatch(&msg);
    |     ----------------- borrow of `sm.current_state` occurs here
 75 |
 76 |     sm.current_state = &s2;
    |     ^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     assignment to borrowed `sm.current_state` occurs here
    |     borrow later used here

 For more information about this error, try `rustc --explain E0506`.
 error: could not compile `expr-traits-1` due to previous error