Initial Commit
The StateMachine<P>::dispatch has an E0499 error need to figure out
how to "fix" this!!

 wink@3900x 22-05-09T19:05:53.170Z:~/prgs/rust/myrepos/expr-traits-1 (main)
 $ cargo check
     Checking expr-traits-1 v0.1.0 (/home/wink/prgs/rust/myrepos/expr-traits-1)
 error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> src/main.rs:12:34
    |
 12 |         self.cur_state().process(self, msg);
    |         ---------------- ------- ^^^^ second mutable borrow occurs here
    |         |                |
    |         |                first borrow later used by call
    |         first mutable borrow occurs here

 For more information about this error, try `rustc --explain E0499`.
 error: could not compile `expr-traits-1` due to previous error